### PR TITLE
chore: upgrade torch points kernels for np 1.21

### PR DESCRIPTION
**Pull request by julianschoep**

### CODE REVIEW

**Review by pevers — APPROVED** [review]
This is looking good!

I'm not super convinced that we should depend on these exact wheels. It is exactly as the comment explains, hard to upgrade stuff like Cuda. Can you add this to the issue tracker that we might want to put back the original dependencies?

**Comment by pevers** [comment]
@julianschoep now that I think a little bit more about it. Let's do it right immediately. So let's not depend on the exact wheel. But let's do this:

```
torch-cluster = "^1.5.6"
...
```

Otherwise we have to fix this again if we decide to upgrade Python

**Comment by julianschoep** [comment]
>@julianschoep now that I think a little bit more about it. Let's do it right immediately. So let's not depend on the exact ?wheel. But let's do this:
>```
>torch-cluster = "^1.5.6"
>...
>```
>Otherwise we have to fix this again if we decide to upgrade Python

@pevers yes lets try that for the non-torch-points-kernels dependencies yes. 

I can create an issue to make multiple wheels for `torch-points-kernels`, but isn't that a bit premature? E.g. better to do that once we really need it/ be lazy in this regard? Maybe once we upgrade python / cuda we won't have this dependency anymore

**Comment by julianschoep** [comment]
@pevers had to revert back the relaxed dependencies. See the updated pyproject.toml for a description of the reason

**Pull request merged**
